# Generated by Django 5.0.2 on 2024-03-06 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PY", "Python"),
                    ("JAVA", "Java"),
                    ("JS", "JavaScript"),
                    ("CPP", "C++"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="pub_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="ref_program",
            field=models.TextField(blank=True),
        ),
    ]
