# Generated by Django 5.0.2 on 2024-03-06 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_alter_question_language_alter_question_pub_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testcase",
            old_name="question_id",
            new_name="question",
        ),
    ]
