# Generated by Django 5.0.2 on 2024-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_question_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                blank=True, choices=[("PY", "python"), ("C", "c")], max_length=20
            ),
        ),
    ]
