# Generated by Django 5.0.2 on 2024-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_alter_question_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="language",
            field=models.CharField(
                blank=True, choices=[("python", "python"), ("c", "c")], max_length=20
            ),
        ),
    ]
