version: '3.8'
services:
  redis:
    image: "redis:7.2.4-alpine"
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery
    command: sh -c "celery -A its_backend worker --loglevel=info"
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c "python3 manage.py migrate --noinput &&
             python3 manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    volumes:
      - db_data:/app

  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-test
    command: >
      sh -c "python3 manage.py migrate --noinput &&
             python3 manage.py loaddata test/test_data.json &&
             python3 manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

volumes:
  redis_data:
  db_data:
