POST http://127.0.0.1:8000/auth/signup
Content-Type: application/json

{"email": "student3@student.com", "password": "12345678" }

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{"email": "tutor1@tutor.com", "password": "12345678"}


###
POST http://127.0.0.1:8000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5MDQ3OTMxLCJpYXQiOjE3MDg5NjE1MzEsImp0aSI6IjM1OWI2NDNmOTIwNjQ1YTVhOGIxZWM2MTkyNzYxNTU0IiwidXNlcl9pZCI6MTh9.0EaK9d859mSPsCvSMrBpzrXhhHbuIMzAiUbLRKKy72w

{ 
    "tokens": {
        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwOTU2NjMzMSwiaWF0IjoxNzA4OTYxNTMxLCJqdGkiOiIyYmUwOWZhNjFlNjU0OTRmOGMyZTQ3MGVjNDU3YWVlOSIsInVzZXJfaWQiOjE4fQ.7wSQD1BHTZo8_MdcruEMyFPVpmDeCO7wvNsKudnrqnw",
        "access_token":  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5MDQ3OTMxLCJpYXQiOjE3MDg5NjE1MzEsImp0aSI6IjM1OWI2NDNmOTIwNjQ1YTVhOGIxZWM2MTkyNzYxNTU0IiwidXNlcl9pZCI6MTh9.0EaK9d859mSPsCvSMrBpzrXhhHbuIMzAiUbLRKKy72w"
    }
}