# Generated by Django 5.0.2 on 2024-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submissiondata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qn_id", models.IntegerField()),
                ("language", models.CharField(default="py", max_length=30)),
                ("submisson_date", models.DateTimeField(auto_now_add=True)),
                ("program", models.CharField(max_length=10000)),
                ("feedback", models.CharField(blank=True, max_length=10000, null=True)),
                ("report", models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
