# Generated by Django 5.0.2 on 2024-03-16 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_alter_submissiondata_submitted_by"),
    ]

    operations = []
