# Generated by Django 5.0.2 on 2024-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_auto_20240316_0651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiondata",
            name="language",
            field=models.CharField(
                blank=True, choices=[("python", "python"), ("c", "c")], max_length=20
            ),
        ),
    ]
