# Generated by Django 4.2.11 on 2024-03-18 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_alter_submissiondata_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submissiondata",
            old_name="report",
            new_name="status",
        ),
    ]
