# Generated by Django 5.0.2 on 2024-04-02 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_rename_report_submissiondata_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiondata",
            name="its_feedback_fix_tutor",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="its_feedback_hint_student",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="language",
            field=models.CharField(
                choices=[("python", "python"), ("c", "c")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="score",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("completed", "completed")],
                max_length=10000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="submission_number",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="submissiondata",
            name="total_score",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
