# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ITS Backend dev PR Check

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Lint with ruff
      run: |
        pip install ruff==0.3.2
        ruff check . --output-format github
    - name: Set up Node
      uses: actions/setup-node@v3
    - name: Start Django server
      run: |
        docker-compose up --build backend-test -d
    - name: Test Postman collections
      run: |
        cd test
        npm install
        newman ITS-API-Test.postman_collection.json

